### PR TITLE
Extra pep8 formatting missed by Black

### PR DESCRIPTION
**Pull request by zhangcandrew**

### CODE REVIEW

**Comment by henrykironde** [comment]
Wondering why it fails on appveyor. Any Idea?

**Comment by zhangcandrew** [comment]
I'm not sure. Looks like it's only failing for Python2.7 also. Is it possible it's running old tests?

It looks like when it's running test_retriever.py, it's hitting this line (which comments out toFix):
image

But that seems to differ from the whats in test_retriever.py.

**Comment by henrykironde** [comment]
I see, I will merge it since i don't see anything that should be affecting the tests

**Comment by henrykironde** [comment]
Thanks @zhangcandrew for the changes

**Pull request merged**
