### PR TITLE
update biotime.json

### PR DESCRIPTION
**Pull request by ss-is-master-chief**

### CODE REVIEW

**Comment by henrykironde** [comment]
```Groovy
char: strings
int: integers
double:floats/decimals
```
You can make boolean as char,  and the numbers as either int or double accordingly.

**Comment by henrykironde** [comment]
looks nice, I will do some testing
Always use this in the future for Json validation .http://jsoneditoronline.org/

**Comment by ss-is-master-chief** [comment]
@henrykironde Thank you. ```Always use this in the future for Json validation .http://jsoneditoronline.org/``` I'll use this!!

**Comment by henrykironde** [comment]
Now it is merged and you can see that in the current PRs

**Comment by ss-is-master-chief** [comment]
@henrykironde Thank you!!

**Pull request merged**
